sonar.organization=jbcom
sonar.projectKey=jbcom_game-mount
sonar.projectName=game-mount
sonar.sources=src
sonar.tests=tests
sonar.exclusions=dist/**,docs/**,coverage/**
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
